### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by srosenbu** [BAMresearch/fenics-reinforcement#3]
Which tests should we do? Can we find an analytical solution? Comparison with fully resolved rebar? Comparison to experiments?

**Comment by mcapp64** [comment]
An analytical solution can be derived by applying the Euler-Bernoulli beam theory. The cuboid is evaluated in the y-z plane, where the deflection is calculated.
The geometrical parameters are given by:

$$
\begin{aligned}
H&: \textrm{height of the cuboid} \\
B&: \textrm{width of the cuboid}\\
E_c&: \textrm{Young's modulus, concrete}\\
E_s&: \textrm{Young's modulus, steel}\\
I_c&: \textrm{Second moment of area, concrete}\\
I_s&: \textrm{Second moment of area, steel}\\
A_r&: \textrm{total area of the rebars in the y-z plane}\\
q_0&: \textrm{distributed force that's applied on the whole width}\\
z&: \textrm{distance between the midpoint (in z) of the rebars and the midpoint of the concrete block, i.e. H/2}
\end{aligned}
$$

By applying the Euler-Bernoulli beam theory, having a fixed bearing on the very left (x=0) and a floating bearing on the very right side (x=B) and applying a distributed force on the whole width, the deflection can be expressed as

$$
\begin{aligned}
w = \frac{1}{24EI}q_0(x⁴-2Bx³+b³x),
\end{aligned}
$$

where

$$
\begin{aligned}
EI = E_c I_c + E_s  I_s
\end{aligned}
$$

with

$$
\begin{aligned}
I_c = \frac{BH³}{12}\\
I_s = \frac{Bh³}{12}+z² A_r
\end{aligned}
$$

where

$$
\begin{aligned}
h = \frac{A_r}{B}
\end{aligned}
$$

**Comment by joergfunger** [comment]
This is not completely correct, you have to compute I with respect to the center of gravity, thus there is a Steiner component (A*r²) for the concrete as well, and z is then not the distance from the reinforcement to the center of concrete, but to the center of gravity for the joint section. e.g. [here](https://pickedshares.com/en/engineering-mechanics-1-exercise-35-calculate-center-of-gravity/). In addition, there is a different [formula](https://skyciv.com/docs/tutorials/section-tutorials/moment-of-inertia-of-a-circle/) for a circular cross section related to the steel. This should not make a huge difference, since $$A_r \cdot z^2$$  is probably much larger than the moment of inertia related to the center of gravity of the steel, but just for correctness :).

**Comment by mcapp64** [comment]
I apologize for the mistake. I did not take the coordinate system's position into account correctly and wasn't consistent with the variables (we are considering the y-z plane, such that y describes the horizontal direction and z the vertical direction), i.e.
[](url)
![image](https://user-images.githubusercontent.com/122089580/220083924-eaffdc4b-1a0d-4c58-b688-f368bf398b61.png)

Assuming the coordinate system is located on the left lower end (y=0, z=0) and now defining 

$$
\begin{aligned}
z_r&: \textrm{distance from z=0 to the rebars}\\
A_r&: \textrm{area of one rebar, assuming circular cross section}\\
A_c&: \textrm{area of concrete}\\
i&: \textrm{amount of rebars}\\
\rho_c&: \textrm{density concrete}\\
\rho_s&: \textrm{density steel}\\
V_c&: \textrm{volume concrete}\\
V_s&: \textrm{volume steel }
\end{aligned}
$$

The center of gravity can be calculated as

$$
z_g = \frac{\rho_c V_c H/2 + \rho_s  V_s z_r}{\rho_c V_c + \rho_s V_s}
$$

with the volumes

$$
\begin{aligned}
V_c &= A_c L\\
V_s &= i A_r L
\end{aligned}
$$

and the second moments of inertia can be calculated as

$$
\begin{aligned}
I_c &= BH^3/12 + (H/2 - z_g)^2A_c\\
&=BH^3/12 + (H/2 - z_g)^2 BH\\
I_s &= A_r^2/(4\pi)i + (z_r-z_g)^2A_r i\\
&= iA_r\left(A_r/(4\pi) + (z_r - z_g)^2 \right)
\end{aligned}
$$

finally yielding

$$
w(y) = \frac{1}{24EI} q_0 \left(y^4 - 2By^3 + B^3y\right)
$$

This should now hopefully be correct.

**Comment by srosenbu** [comment]
Could it be that you confused $B$ and $L$ at some point? Because if I run your code https://github.com/BAMresearch/fenics-reinforcement/blob/reinf_stresses/test/analytical_solution.py and plot the solution, I get a nice plot if I only plot $w(x)$ for $x\in[0,B]$ with $0$ at the boundaries and a maximum in the middle, but for $x\in[0,L]$ the plot looks weird. Also the values are off by approximately a factor of $10^3$, so maybe you can have a short look on that.
Plot from $0$ to $B$
![Figure_2](https://user-images.githubusercontent.com/69848361/220158369-8c61fb3a-364b-4a51-ad6d-1b7cab6a46f0.png)
Plot from $0$ to $L$
![Figure_1](https://user-images.githubusercontent.com/69848361/220158186-26f15f76-c9db-418f-96b5-4760b3829059.png)

**Comment by srosenbu** [comment]
Okay, I may have had some error because I used the nonlinear solver wrong. Without reinforcement and with a linear solver, the plots are almost identical. I will change the test accordingly and hopefully with reinforcements, everything will be fine as well

**Comment by srosenbu** [comment]
We resolved this issue by testing another problem, since the dirichlet boundary conditions caused _warped_ elements. Merged in https://github.com/BAMresearch/fenics-reinforcement/pull/12.
